name: Validation

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - run: |
          npm ci
          npm test
